name: Atlantis Chan

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: "Deploy via SSH"
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  # Ensure the script stops if any command fails
                  set -e

                  if [ ! -d "$HOME/AtlantisChan" ]; then
                      # Added missing slash after github.com
                      git clone https://github.com{{ github.repository }}.git ~/AtlantisChan
                  fi

                  # Explicitly change to the directory before running npm
                  cd ~/AtlantisChan
                  
                  # If the folder already existed, pull the latest changes
                  if [ -d ".git" ]; then
                      git pull origin main
                  fi

                  npm install --production
